import csv

if __name__ == '__main__':

    # open a csv file that was generated by excel
    file_path = "data/csv/bio.csv"
    headers = []
    total_sections = 0
    starting_pages = 0
    removed_pages = 0
    ending_pages = 0

    with open(file_path, encoding='utf8', newline='') as csv_file:
        reader = csv.reader(csv_file, delimiter=',')
        # loop over the contents
        i = 0
        for row in reader:
            # Grab the headers
            if i == 0:
                print("Headers here.")
            # is this a section
            elif not row[0].startswith("http") and not row[0] == "":
                print("Here is a section")
                print(row[0])
            elif row[0].startswith("http"):
                if not row[0].endswith("index.html"):
                    print(row[0])
                else:
                    print("86 => " + row[0])
            else:
                continue
            i += 1

    #print("{} pages were removed.".format(removed_pages))

    # remove any occurrence of index.html

    # get counts of all the things

    # save a modified csv in a dialect that excel likes
